from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph, START, END
from app.api.schema.chat import ChatRequest
from app.api.schema.chat_state import ChatState
from app.services.chat.nodes import generate_content
from langchain_core.messages import HumanMessage

checkpoint = MemorySaver()

# Define a simple state graph using the TypedDict state
graph = StateGraph(ChatState)

graph.add_node("generate_content", generate_content)

graph.add_edge(START, 'generate_content')
graph.add_edge('generate_content', END)

# Compile the graph
app_graph = graph.compile(checkpointer=checkpoint)

import json
import uuid

def llm_service(request: ChatRequest):
    # Prepare the initial message
    initial_message = HumanMessage(content=request.message)

    # Invoke the compiled graph with the initial state
    result = app_graph.invoke(
        {"messages": [initial_message], "session_id": request.session_id}, 
        config={"configurable": {"thread_id": request.session_id}}
    )

    # Extract the last message generated by the LLM
    final_message = result['messages'][-1].content
    professional_ids = []

    try:
        # Check if the LLM returned the completed JSON payload
        parsed_content = json.loads(final_message)
        if isinstance(parsed_content, dict) and parsed_content.get("status") == "COMPLETED":
            # Format the user-facing message
            final_message = (
                f"Thank you! I have all the information needed. Here is your request:\n"
                f"- Service: {parsed_content.get('service')}\n"
                f"- Budget: {parsed_content.get('budget')}\n"
                f"- Date/Time: {parsed_content.get('time')}\n"
                f"- Preferred Location: {parsed_content.get('location')}"
            )
            # Add a random ID to the professionalId list
            professional_ids.append(str(uuid.uuid4()))
    except (json.JSONDecodeError, TypeError):
        # AI is still conversing to gather information
        pass

    return {
        'session_id': request.session_id,
        'message': final_message,
        'professionalId': professional_ids
    }
