from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph, START, END
from app.api.schema.chat import ChatRequest
from app.api.schema.chat_state import ChatState
from app.services.chat.nodes import generate_content
from langchain_core.messages import HumanMessage

checkpoint = MemorySaver()

# Define a simple state graph using the TypedDict state
graph = StateGraph(ChatState)

graph.add_node("generate_content", generate_content)

graph.add_edge(START, 'generate_content')
graph.add_edge('generate_content', END)

# Compile the graph
app_graph = graph.compile(checkpointer=checkpoint)

def llm_service(request: ChatRequest):
    # Prepare the initial message
    initial_message = HumanMessage(content=request.message)

    # Invoke the compiled graph with the initial state
    result = app_graph.invoke(
        {"messages": [initial_message], "session_id": request.session_id}, 
        config={"configurable": {"thread_id": request.session_id}}
    )

    # Extract the last message generated by the LLM
    final_message = result['messages'][-1].content

    return {
        'session_id': request.session_id,
        'message': final_message,
        'professionalId': []
    }
